# TCL File Generated by Component Editor 17.0
# Sun Oct 01 18:06:14 MSK 2017
# DO NOT MODIFY


# 
# rgb_led_matrix "RGB LED Matrix Driver" v1.0
# Evgeny Sabelskiy 2017.10.01.18:06:14
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module rgb_led_matrix
# 
set_module_property DESCRIPTION ""
set_module_property NAME rgb_led_matrix
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Evgeny Sabelskiy"
set_module_property DISPLAY_NAME "RGB LED Matrix Driver"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL rgb_led_matrix
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file rgb_led_matrix.sv VERILOG PATH rgb_led_matrix.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter matrix_width INTEGER 64 leds
set_parameter_property matrix_width DEFAULT_VALUE 64
set_parameter_property matrix_width DISPLAY_NAME matrix_width
set_parameter_property matrix_width TYPE INTEGER
set_parameter_property matrix_width UNITS None
set_parameter_property matrix_width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property matrix_width DESCRIPTION leds
set_parameter_property matrix_width AFFECTS_GENERATION false
set_parameter_property matrix_width HDL_PARAMETER true
add_parameter matrix_height INTEGER 32 leds
set_parameter_property matrix_height DEFAULT_VALUE 32
set_parameter_property matrix_height DISPLAY_NAME matrix_height
set_parameter_property matrix_height TYPE INTEGER
set_parameter_property matrix_height UNITS None
set_parameter_property matrix_height ALLOWED_RANGES -2147483648:2147483647
set_parameter_property matrix_height DESCRIPTION leds
set_parameter_property matrix_height AFFECTS_GENERATION false
set_parameter_property matrix_height HDL_PARAMETER true
add_parameter number_of_matrix INTEGER 1 ""
set_parameter_property number_of_matrix DEFAULT_VALUE 1
set_parameter_property number_of_matrix DISPLAY_NAME number_of_matrix
set_parameter_property number_of_matrix WIDTH ""
set_parameter_property number_of_matrix TYPE INTEGER
set_parameter_property number_of_matrix UNITS None
set_parameter_property number_of_matrix ALLOWED_RANGES -2147483648:2147483647
set_parameter_property number_of_matrix DESCRIPTION ""
set_parameter_property number_of_matrix AFFECTS_GENERATION false
set_parameter_property number_of_matrix HDL_PARAMETER true
add_parameter color_depth INTEGER 256 ""
set_parameter_property color_depth DEFAULT_VALUE 256
set_parameter_property color_depth DISPLAY_NAME color_depth
set_parameter_property color_depth TYPE INTEGER
set_parameter_property color_depth UNITS None
set_parameter_property color_depth ALLOWED_RANGES -2147483648:2147483647
set_parameter_property color_depth DESCRIPTION ""
set_parameter_property color_depth AFFECTS_GENERATION false
set_parameter_property color_depth HDL_PARAMETER true
add_parameter start_addr STD_LOGIC_VECTOR 0 ""
set_parameter_property start_addr DEFAULT_VALUE 0
set_parameter_property start_addr DISPLAY_NAME start_addr
set_parameter_property start_addr WIDTH 32
set_parameter_property start_addr TYPE STD_LOGIC_VECTOR
set_parameter_property start_addr UNITS None
set_parameter_property start_addr DESCRIPTION ""
set_parameter_property start_addr AFFECTS_GENERATION false
set_parameter_property start_addr HDL_PARAMETER true


# 
# display items
# 
add_display_item "" "Matrix Dimension" GROUP ""
add_display_item "" Chaining GROUP ""
add_display_item "" Colors GROUP ""
add_display_item "" "Start Address" GROUP ""
add_display_item "" Memory GROUP ""


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point matrix_wire
# 
add_interface matrix_wire conduit end
set_interface_property matrix_wire associatedClock clk
set_interface_property matrix_wire associatedReset reset
set_interface_property matrix_wire ENABLED true
set_interface_property matrix_wire EXPORT_OF ""
set_interface_property matrix_wire PORT_NAME_MAP ""
set_interface_property matrix_wire CMSIS_SVD_VARIABLES ""
set_interface_property matrix_wire SVD_ADDRESS_GROUP ""

add_interface_port matrix_wire led_r0 led_r0 Output 1
add_interface_port matrix_wire led_g0 led_g0 Output 1
add_interface_port matrix_wire led_b0 led_b0 Output 1
add_interface_port matrix_wire led_r1 led_r1 Output 1
add_interface_port matrix_wire led_g1 led_g1 Output 1
add_interface_port matrix_wire led_b1 led_b1 Output 1
add_interface_port matrix_wire led_clk led_clk Output 1
add_interface_port matrix_wire led_lat led_lat Output 1
add_interface_port matrix_wire led_oe led_oe Output 1
add_interface_port matrix_wire led_row led_row Output 4


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point matrix_ram1
# 
add_interface matrix_ram1 avalon start
set_interface_property matrix_ram1 addressUnits SYMBOLS
set_interface_property matrix_ram1 associatedClock clk
set_interface_property matrix_ram1 associatedReset reset
set_interface_property matrix_ram1 bitsPerSymbol 8
set_interface_property matrix_ram1 burstOnBurstBoundariesOnly false
set_interface_property matrix_ram1 burstcountUnits WORDS
set_interface_property matrix_ram1 doStreamReads false
set_interface_property matrix_ram1 doStreamWrites false
set_interface_property matrix_ram1 holdTime 0
set_interface_property matrix_ram1 linewrapBursts false
set_interface_property matrix_ram1 maximumPendingReadTransactions 0
set_interface_property matrix_ram1 maximumPendingWriteTransactions 0
set_interface_property matrix_ram1 readLatency 0
set_interface_property matrix_ram1 readWaitTime 1
set_interface_property matrix_ram1 setupTime 0
set_interface_property matrix_ram1 timingUnits Cycles
set_interface_property matrix_ram1 writeWaitTime 0
set_interface_property matrix_ram1 ENABLED true
set_interface_property matrix_ram1 EXPORT_OF ""
set_interface_property matrix_ram1 PORT_NAME_MAP ""
set_interface_property matrix_ram1 CMSIS_SVD_VARIABLES ""
set_interface_property matrix_ram1 SVD_ADDRESS_GROUP ""

add_interface_port matrix_ram1 ram1_read read Output 1
add_interface_port matrix_ram1 ram1_readdata readdata Input 32
add_interface_port matrix_ram1 ram1_byteenable byteenable Output 4
add_interface_port matrix_ram1 ram1_address address Output 13
add_interface_port matrix_ram1 ram1_readdatavalid readdatavalid Input 1
add_interface_port matrix_ram1 ram1_waitrequest waitrequest Input 1


# 
# connection point matrix_ram2
# 
add_interface matrix_ram2 avalon start
set_interface_property matrix_ram2 addressUnits SYMBOLS
set_interface_property matrix_ram2 associatedClock clk
set_interface_property matrix_ram2 associatedReset reset
set_interface_property matrix_ram2 bitsPerSymbol 8
set_interface_property matrix_ram2 burstOnBurstBoundariesOnly false
set_interface_property matrix_ram2 burstcountUnits WORDS
set_interface_property matrix_ram2 doStreamReads false
set_interface_property matrix_ram2 doStreamWrites false
set_interface_property matrix_ram2 holdTime 0
set_interface_property matrix_ram2 linewrapBursts false
set_interface_property matrix_ram2 maximumPendingReadTransactions 0
set_interface_property matrix_ram2 maximumPendingWriteTransactions 0
set_interface_property matrix_ram2 readLatency 0
set_interface_property matrix_ram2 readWaitTime 1
set_interface_property matrix_ram2 setupTime 0
set_interface_property matrix_ram2 timingUnits Cycles
set_interface_property matrix_ram2 writeWaitTime 0
set_interface_property matrix_ram2 ENABLED true
set_interface_property matrix_ram2 EXPORT_OF ""
set_interface_property matrix_ram2 PORT_NAME_MAP ""
set_interface_property matrix_ram2 CMSIS_SVD_VARIABLES ""
set_interface_property matrix_ram2 SVD_ADDRESS_GROUP ""

add_interface_port matrix_ram2 ram2_address address Output 13
add_interface_port matrix_ram2 ram2_byteenable byteenable Output 4
add_interface_port matrix_ram2 ram2_read read Output 1
add_interface_port matrix_ram2 ram2_readdata readdata Input 32
add_interface_port matrix_ram2 ram2_readdatavalid readdatavalid Input 1
add_interface_port matrix_ram2 ram2_waitrequest waitrequest Input 1

